name: Automate QCOM build process

on:
  push:
    #trigger upon any .xml modification at any depth on specified branch
    branches:
      - 'master'
    paths:
      - "**/*.xml"

  #allows for manual workflow execution
  workflow_dispatch:

  #scheduled nightly builds for development manifests
  schedule: 
    - cron: '00 23 * * *' #nightly at 23:00 UTC

permissions:
  contents: read

defaults:
  run:
    shell: bash -euo pipefail {0}

env:
  #debug variables for forcing specified builds for testing
  BUILD_DEBUG: "1"
  DEBUG_LIST: ''

jobs:
  get_changed_manifests:
    runs-on: [self-hosted, Linux, X64, qcom]
    outputs:
      manifest_list: ${{ steps.build_manifest_matrix.outputs.manifest_list || '[]' }} #list of manifests to build
      dev_state_log: ${{ steps.get_scheduled_manifests.outputs.dev_state_log || '' }} #for scheduled logging dev builds

    #checkout the current repository under 'manifest_repo' => Access manifests
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0 #set to 0 ensure that previous commit can be accessed for diff checks
        path: manifest_repo   
        
    #checkout qualcomm-ci repo under 'qualcomm_ci' => Access build matrix script located there
    - uses: actions/checkout@v5
      with:
          repository: imd-tec/qualcomm-ci
          ref: development
          token: ${{ secrets.QCI_DEPLOY_PAT }}
          persist-credentials: false
          path: qualcomm_ci
    
    - name: Get event details
      run: echo "Triggered by ${{ github.event_name }} event by ${{ github.triggering_actor}} on ${{ github.ref }}."

    ## CREATE MANIFESTS.TXT BASED ON EVENT TRIGGER TYPE

    #PUSH => build added or modified xml manifests
    - name: Diff-check commits to determine added or modified manifests
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' && env.BUILD_DEBUG == '1'
      working-directory: qualcomm_ci
      run: | 
        bash ./scripts/get-changed-manifests.sh \
        --manifest_repo_path "$GITHUB_WORKSPACE/manifest_repo" \
        --before_sha "${{ github.event.before }}" \
        --current_sha "${{ github.event.after }}"
        
    #SCHEDULE => attempt development build/s, dependant on meta-layer changes
    - name: Poll development manifest metalayers for changes
      id: get_scheduled_manifests
      if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && env.BUILD_DEBUG == '2'
      working-directory: qualcomm_ci
      run: |
        bash ./scripts/poll-development-repo.sh \
        --manifest_repo_path "$GITHUB_WORKSPACE/manifest_repo" \
        --manifest_repo_name "${{ github.repository }}"

    #MANUAL => if the BUILD_DEBUG flag is set, force line-seperated builds outlined in DEBUG_LIST
    - name: Get manifests from debug list
      if: github.event_name == 'workflow_dispatch' && env.DEBUG_LIST != '' && env.BUILD_DEBUG == '3'
      #as GitHub Action environment variables are strings, we need to read the debug list into an array line-by-line for sanitation
      run: |
        mapfile -t MANIFESTS <<< "$DEBUG_LIST"
        for mani in "${MANIFESTS[@]}"; do
          mani=$(printf '%s' "$mani" | xargs)  #xargs to trim any whitespace
          echo "$mani" >> "$RUNNER_TEMP/manifests.txt"
        done
    
    #create a serialized json array containing each manifest's build details, as specified in the corresponding project config yaml (e.g., imdt-qcom-bsp.yml)
    - name: Build manifest matrix
      if: success() 
      id: build_manifest_matrix
      working-directory: qualcomm_ci
      run: | 
        if [ -f "$RUNNER_TEMP/manifests.txt" ]; then
          python ./scripts/build-manifest-matrix.py \
          --manifest_list "$RUNNER_TEMP/manifests.txt" \
          --manifest_path "$GITHUB_WORKSPACE/manifest_repo"
        else
          echo -e "\nNo manifests to build."
        fi

  build:
    #trigger a parallel build job for each manifest using the generated matrix
    needs: get_changed_manifests
    if: ${{ needs.get_changed_manifests.outputs.manifest_list != '[]' }}
    strategy:
      #do not fail the entire job if one build instance fails
      fail-fast: false
      matrix: 
        include: ${{ fromJson(needs.get_changed_manifests.outputs.manifest_list) }}
    uses: imd-tec/qualcomm-ci/.github/workflows/imdt-build-qcom-bsp.yml@master
    secrets: inherit
    with:
      MANIFEST_REPOSITORY: ${{ github.event.repository.html_url }}
      MANIFEST_BRANCH: ${{ github.ref_name }}  
      MANIFEST_XML: ${{ matrix.manifest }}    
      BUILD_NAME: ${{ matrix.name }}
      BUILD_VERSION: ${{ matrix.version }}
      BUILD_KERNEL_VARIANT: ${{ matrix.kernel_variant }}
      BUILD_MACHINE: ${{ matrix.machine }}
      BUILD_DISTRO: ${{ matrix.distro }}
      BUILD_IMAGE: ${{ matrix.image }}
      BASE_DOCKER_IMAGE: ${{ matrix.docker }}
      BUILD_PATCH_SCRIPT_PATH: ${{ matrix.patch_script_path }}
      BUILD_RELEASE_NAME: ${{ matrix.release_name }}
      PYENV: ${{ matrix.pyenv }}
      QCS_SOURCES: ${{ matrix.qcs_sources }}
      PATCH_FALLBACK_PATH: ${{ matrix.patch_fallback_path }}
      SKIP_STEPS: ${{ matrix.skip_steps }}
      DEV_STATE_LOG: ${{ needs.get_changed_manifests.outputs.dev_state_log}}

