name: Build qc bsp v1.0.0 public
run-name: echo "${{ github.actor }} is building qc bsp v1.0.0 bsp"

defaults:
  run:
    #fail on any error
    shell: bash -ieo pipefail {0}

on:
  push:
    branches:
      - master

  #workflow is executed every night at 9
  workflow_dispatch:
  # schedule:
    # - cron: '0 21 * * *'

jobs:
  build-qualcomm-bsp:
    #specify labels to run on qcom desktop
    runs-on: [self-hosted, linux, x64, qcom-ci]

    steps:
      - run: echo "Triggered by ${{ github.event_name }} event."
      - run: echo "Branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Checkout repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - name: Show docker images
        run: |
          docker images

      - name: Run Qualcomm container
        id: qc_env_container
        run: |
          cd ${{ github.workspace }}
          container_name="ci_qualcomm_$(date +%s)"
          echo "CONTAINER_NAME=$container_name" >> $GITHUB_ENV
          chmod +x ./qualcomm-docker-run.sh
          ./qualcomm-docker-run.sh \
          --sdk \
          --cdt \
          --container-name $container_name \
          --source-repo qcs8550-le-1-0_amss_standard_oem_apqgps \
          --docker-version 0.5.1 \
          --manifest-repo https://github.com/imd-tec/imdt-qcom-manifest.git \
          --manifest-branch kirkstone \
          --manifest-xml default.xml \


      - name: Verify that the container is running
        run: |
          docker ps | grep $CONTAINER_NAME

      - name: Kill container if it's still alive
        if: always()
        run: |
          cd ${{ github.workspace }}
          chmod +x ./stop-container.sh
          ./stop-container.sh $CONTAINER_NAME 
      
