#Reusable workflow triggerd by workflow_call from external manifest repo
name: Build qcom BSP (reusable)

defaults:
  run:
    shell: bash -ueo pipefail {0}

on:
  workflow_call:
      inputs:
        MANIFEST_REPOSITORY:
          required: true
          description: Manifest repository URL
          type: string            

        MANIFEST_BRANCH:
          required: true
          description: Branch of manifest in repository
          type: string   

        MANIFEST_XML:
          required: true
          description: Path to the manifest XML file in branch 
          type: string

        BUILD_NAME:
          required: true
          description: Name of the build (e.g. imsu_glasses_bsp)
          type: string
        
        BUILD_VERSION:
          required: true
          description: Version of the manifest (e.g. 1.0.0)
          type: string     

        BUILD_KERNEL_VARIANT:
          required: true
          description: Kernel variant to use (e.g. gki-kernel)
          type: string

        BUILD_MACHINE:
          required: true
          description: Target hardware machine (e.g. imdt-qcs8550-sbc)
          type: string      

        BUILD_DISTRO:
          required: true
          description: Build distribution (e.g. imdt-distro-debug)
          type: string

        BUILD_IMAGE:
          required: true
          description: Target image to build (e.g. imdt-image-weston)
          type: string      

        BUILD_PROJECT_PATH:
          required: true
          description: Local path on runner to project directory (e.g. /mnt/nvme1/qcom_ci/builds/IMSU/GLASSES)
          type: string       

        BUILD_DOCKER:
          required: true
          description: Docker base image to use (e.g. imdtec/imdt-qualcomm-build-setup:0.5.1)
          type: string

        BUILD_HAS_PATCHES:
          required: true
          description: Whether the build has patches (1 or 0)
          type: string

        BUILD_PATCH_SCRIPT_PATH:
          required: true
          description: Path to IMDT patch build script (e.g. apps_proc/poky/meta-imsu-glasses/tools/imdt-patch-qcs8550-build.sh)
          type: string

        BUILD_RELEASE_NAME:
          required: true
          description: Release artifact name (e.g. imsu_glasses_prebuilt_release)
          type: string     
        
        PYENV:
          required: true
          description: Python environment version to use (e.g. 3.8.16)
          type: string
          default: "3.8.16"

        QCS_SOURCES:
          required: true
          description: Qualcomm source files to use (e.g. qcs8550-le-1-0_amss_standard_oem_apqgps)
          type: string

        SKIP_STEPS:
          required: false
          description: Build steps to skip, defined by 'contains' conditionals below (e.g. [sync_repos, build_hlos])
          type: string

  workflow_dispatch:

env:
  #Build constants
  CONTAINER_NAME: "ci_qualcomm_${{ github.run_id }}"
  CI_DIR: "/mnt/nvme1/qcom_ci"
  DOCKER_EXEC: docker exec -t -u dev

  #Workflow development variables
  CLEAN_UP: "1"
  DEBUG_SKIP_SRC: "0"

jobs:
  build-qualcomm-bsp:
    #specify labels to run on qcom desktop
    runs-on: [self-hosted, linux, x64, qcom]
    env:
      MANIFEST_REPOSITORY: ${{ inputs.MANIFEST_REPOSITORY }}
      MANIFEST_BRANCH: ${{ inputs.MANIFEST_BRANCH }}
      MANIFEST_XML: ${{ inputs.MANIFEST_XML }}
      BUILD_NAME: ${{ inputs.BUILD_NAME }}
      BUILD_VERSION: ${{ inputs.BUILD_VERSION }}
      KERNEL_VARIANT: ${{ inputs.BUILD_KERNEL_VARIANT }}
      MACHINE: ${{ inputs.BUILD_MACHINE }}
      DISTRO: ${{ inputs.BUILD_DISTRO }}
      IMAGE: ${{ inputs.BUILD_IMAGE }}
      #This evaluates to [project_path]/[version]
      BUILD_PROJECT_PATH: ${{ format('{0}/{1}', inputs.BUILD_PROJECT_PATH, inputs.BUILD_VERSION) }}
      BUILD_DOCKER: ${{ inputs.BUILD_DOCKER }}
      HAS_PATCHES: ${{ inputs.BUILD_HAS_PATCHES }}
      PATCH_SCRIPT_PATH: ${{ inputs.BUILD_PATCH_SCRIPT_PATH }}
      RELEASE_NAME: ${{ inputs.BUILD_RELEASE_NAME }}
      PYENV: ${{ inputs.PYENV }}
      QCS_SOURCES: ${{ inputs.QCS_SOURCES }}
      SKIP_STEPS: ${{ inputs.SKIP_STEPS }}

    steps:      
      - name: Set repository workspace
        #explicitly checkout into repository. Required if triggered from external repo.
        uses: actions/checkout@v5
        with:
            repository: imd-tec/qualcomm-ci
            ref: master
            ssh-key: ${{ secrets.QCI_DEPLOY_KEY }}
            path: ci_repo

      - name: Validate inputs and create build project directory
        run: |
          #verify that CI directory is included in project path
          if grep -q "${CI_DIR}" <<< "${BUILD_PROJECT_PATH}"; then
          echo "Using project path: ${BUILD_PROJECT_PATH}"
          else
          echo "ERROR: project path ${BUILD_PROJECT_PATH} is invalid. It must be under ${CI_DIR}."
          exit 1
          fi

          #create and change to build project directory
          mkdir -p "${BUILD_PROJECT_PATH}" && cd "${BUILD_PROJECT_PATH}"

      - name: Extract build sources files into build directory
        if: ${{ !contains(env.SKIP_STEPS, 'extract_sources') }} || env.DEBUG_SKIP_SRC != '1'
        working-directory: ${{ github.workspace }}/ci_repo/scripts
        run: bash extract-sources.sh
          
      - name: Create Docker image, build container and initialize user permissions & ownership
        if: ${{ !contains(env.SKIP_STEPS, 'build_container') }}
        timeout-minutes: 20
        run: |
          #get host user and group IDs to pass to container
          export HOST_UID=$(id -u)
          export HOST_GID=$(id -g)

          #affix base BUILD_DOCKER version to new image name
          IMAGE_NAME="imdt-qualcomm-ci:${BUILD_DOCKER##*:}"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

          #build container image from BASE_IMAGE and set entry point
          docker build -f "${CI_DIR}/docker/qc_ci_docker" \
          --build-arg BASE_IMAGE="${BUILD_DOCKER}" \
          -t "$IMAGE_NAME" \
          "${CI_DIR}"/scripts/docker_scripts/

          #run the container
          #pass ID's to entry-point script (scripts/for_docker/docker_entry_point.sh) to setup user permissions and ownership
          docker run --rm -d \
          --name "$CONTAINER_NAME" \
          -e MANIFEST_REPOSITORY="$MANIFEST_REPOSITORY" \
          -e MANIFEST_BRANCH="$MANIFEST_BRANCH" \
          -e MANIFEST_XML="$MANIFEST_XML" \
          -e IMAGE="$IMAGE" \
          -e RELEASE_NAME="$RELEASE_NAME" \
          -e BUILD_VERSION="$BUILD_VERSION" \
          -e KERNEL_VARIANT="$KERNEL_VARIANT" \
          -e QCOM_ROOT_DIR="/home/dev/Qualcomm/${QCS_SOURCES}" \
          -e PYENV="$PYENV" \
          -e MACHINE="$MACHINE" \
          -e DISTRO="$DISTRO" \
          -e PATCH_SCRIPT_PATH="$PATCH_SCRIPT_PATH" \
          -v "${BUILD_PROJECT_PATH}:/home/dev/Qualcomm" \
          -v "${CI_DIR}/scripts/docker_scripts/:/home/dev/tools/" \
          "$IMAGE_NAME" "$HOST_UID" "$HOST_GID" \
          sleep infinity

          #stream entry point script logs
          docker logs -f "${CONTAINER_NAME}" &
          LOG_PID=$!

          #wait for entry script to signal completion
          until docker exec "${CONTAINER_NAME}" test -f /tmp/ready; do sleep 2; done

          #kill log stream
          kill $LOG_PID || true

          #verify that IDs are correct and ownership has been transferred correctly
          result=$($DOCKER_EXEC "${CONTAINER_NAME}" bash -c 'id')

          if [[ $result != *"uid=$HOST_UID"* && $result != *"gid=$HOST_GID"* ]]; then
            echo "ERROR: User IDs do not match"
            exit 1
          fi

      - name: Build netrc
        if: ${{ !contains(env.SKIP_STEPS, 'build_netrc') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '

          #build netrc
          bash /home/dev/tools/build_netrc.sh && test -f /home/dev/.netrc
          '

      - name: Patch and synchronize repos
        if: ${{ !contains(env.SKIP_STEPS, 'sync_repos') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '

          if [ -d "/home/dev/Qualcomm/patches" ]; then
            PATCHFILE="/home/dev/Qualcomm/patches/sync_snap_v2_remove_chipcode_copy.patch"
            TARGET="${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/sync_snap_v2.sh"
            #batch to bypass user prompts
            patch --batch "$TARGET" "$PATCHFILE" 
          fi

          #sync repos
          bash /home/dev/build_scripts/sync_repos.sh -u "$MANIFEST_REPOSITORY" -b "$MANIFEST_BRANCH" -m "$MANIFEST_XML"
          '

      - name: Configure kernel directories
        if: ${{ !contains(env.SKIP_STEPS, 'conf_kernel') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          bash -x /home/dev/build_scripts/setup_kernel.sh
          '

      - name: Apply IMDT patches to Qualcomm source
        if: ${{ !contains(env.SKIP_STEPS, 'apply_patches') }}
        run: | 
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          #applying IMDT patches to QC source
          bash "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/${PATCH_SCRIPT_PATH}"
          '
      
      - name: Configure contents.xml
        if: ${{ !contains(env.SKIP_STEPS, 'conf_contents') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          python3 /home/dev/build_scripts/configure_contents_xml.py \
          --distro "${DISTRO}" \
          --machine "${MACHINE}" \
          --images "${IMAGE}"
          ' 

      - name: Build kernel
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          bash /home/dev/build_scripts/build_kernel.sh \
          --lto "thin" --jobs 8 \
          --build_variant "${KERNEL_VARIANT}" \
          --build_output_dir "../out/msm-kernel-kalama_le-${KERNEL_VARIANT}"
          '

      - name: Build HLOS
        if: ${{ !contains(env.SKIP_STEPS, 'build_hlos') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          cd "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/poky"

          patch ./meta-qti-bsp/classes/populate_sdk_qti.bbclass \
          "/home/dev/Qualcomm/patches/populate_sdk_qti_remove_llvm_native.patch"
          
          cp -rn "${QCOM_ROOT_DIR}/LE.FRAMEWORK.2.0.r1/apps_proc/poky/"* \
                  "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/poky/"

          cp -rn "${QCOM_ROOT_DIR}/LE.FRAMEWORK.2.0.r1/apps_proc/src/"* \
                  "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/src/"
          '

      - name: Bitbake fetch sources
        if: ${{ !contains(env.SKIP_STEPS, 'bitbake_fetch') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          #set Yocto environment
          source /home/dev/tools/setup_yocto_env.sh

          bitbake "${IMAGE}" --runall=fetch
          '

      - name: Bitbake build image
        if: ${{ !contains(env.SKIP_STEPS, 'bitbake_build') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          #set Yocto environment
          source /home/dev/tools/setup_yocto_env.sh
          
          #build image
          bitbake "${IMAGE}"
          '

      - name: Generate Yocto SDK
        if: ${{ !contains(env.SKIP_STEPS, 'build_sdk') }}
        continue-on-error: true
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          #set Yocto environment
          source /home/dev/tools/setup_yocto_env.sh

          bitbake ${IMAGE} -c populate_sdk
          
          #locate generated SDK script and rename
          SDK_DIR="${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/build-${DISTRO}/tmp-glibc/deploy/sdk/"
          #output name format: [release_name_without_prebuilt_suffix]-sdk-v[build_version].sh
          OUTPUT_NAME="${SDK_DIR}/${RELEASE_NAME%_prebuilt*}-sdk-v${BUILD_VERSION}.sh"
          
          #verify that there is exactly one sh script in SDK_DIR
          cd "$SDK_DIR"
          sdk_sh="$(find -maxdepth 1 -type f -name '*.sh')"

          if [[ -z "$sdk_sh" ]]; then
            echo "ERROR: No SDK files found in ${SDK_DIR}"
            exit 1
          fi

          #rename SDK script to output_name
          mv -- "$sdk_sh" "$OUTPUT_NAME"
          '
      
      - name: Build non-HLOS components
        if: ${{ !contains(env.SKIP_STEPS, 'build_non_hlos') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          set -x
          bash -x /home/dev/build_scripts/build_non_hlos.sh --build all
          '

      - name: Create release artifact
        if: ${{ !contains(env.SKIP_STEPS, 'create_release') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          set -xe
          FULL_RELEASE_NAME="${RELEASE_NAME}_v${BUILD_VERSION}"
          RELEASE_DIR="/home/dev/Qualcomm/${FULL_RELEASE_NAME}"

          #if release directory already exists, remove it
          [ -d "$RELEASE_DIR" ] && rm -rf "$RELEASE_DIR"
          
          #create new release artifact
          cd /home/dev/build_scripts
          python3 create_release.py \
           -r "$RELEASE_DIR" \
           -x "${QCOM_ROOT_DIR}/contents.xml" \
           -b "${QCOM_ROOT_DIR}"
          
          #create prebuilt tarball 
          tar -C "/home/dev/Qualcomm/" -czf "${FULL_RELEASE_NAME}.tar.gz" "${FULL_RELEASE_NAME}"

          #verify tarball creation and non-compresssed directory
          if [ -f "/home/dev/Qualcomm/${FULL_RELEASE_NAME}.tar.gz" ]; then
            echo "Release artifact created at /home/dev/Qualcomm/${FULL_RELEASE_NAME}.tar.gz"
            echo "Cleaning up temporary release directory..."
            if [ -d "$RELEASE_DIR" ]; then
              rm -rf "$RELEASE_DIR"
            fi
          else
            echo "ERROR: Release artifact creation failed."
            exit 1
          fi
          '

      - name: Clean up container and image
        if: ${{ always() && env.CLEAN_UP == '1' }}
        run: |
          chmod +x $GITHUB_WORKSPACE/scripts/stop-container.sh
          bash $GITHUB_WORKSPACE/scripts/stop-container.sh ${CONTAINER_NAME} ${IMAGE_NAME}

      - name: Clean up source files
        if:  ${{ always() && env.CLEAN_UP == '1' }}
        run: |
          set -euo pipefail -x
          [ -d "${BUILD_PROJECT_PATH:?}/qcs8550-le-1-0_amss_standard_oem_apqgps" ] && \
          rm -rf "${BUILD_PROJECT_PATH:?}/qcs8550-le-1-0_amss_standard_oem_apqgps"

          if [ "$HAS_PATCHES" == 1 ]; then
            [ -d "${BUILD_PROJECT_PATH:?}/patches" ] && \
              rm -rf "${BUILD_PROJECT_PATH:?}/patches"
          fi            



         