#Reusable workflow triggerd by workflow_call from external manifest repo
name: Build qcom BSP (reusable)

defaults:
  run:
    shell: bash -ueo pipefail {0}

on:
  workflow_call:
      inputs:
        mani_repo:
          required: true
          description: Manifest repository URL
          type: string            

        mani_branch:
          required: true
          description: Branch of manifest repository
          type: string   

        mani_xml:
          required: true
          description: Path to the manifest XML file
          type: string

        build_name:
          required: true
          description: Name of the build
          type: string

        build_version:
          required: true
          description: Version of the manifest
          type: string     

        build_machine:
          required: true
          description: Build machine
          type: string      

        build_distro:
          required: true
          description: Build distro
          type: string      
                
        build_image:
          required: true
          description: Build image
          type: string      

        build_project_path:
          required: true
          description: Local path on runner to project directory
          type: string       

        build_docker:
          required: true
          description: Docker image to use
          type: string

        build_patches:
          required: true
          description: Whether the build has patches
          type: string

        build_patch_script_path:
          required: true
          description: Path to IMDT patch build script
          type: string

        build_release_name:
          required: true
          description: Release artifact name
          type: string     
        
        PYENV:
          required: true
          description: Python environment version
          type: string
          default: "3.8.16"

        QCS_SOURCES:
          required: true
          description: Qualcomm source files to use
          type: string

        SKIP_STEPS:
          required: false
          description: Steps to skip during the build
          type: string

  workflow_dispatch:

env:
  #Build constants
  CONTAINER_NAME: "ci_qualcomm_${{ github.run_id }}"
  CI_DIR: "/mnt/nvme1/qcom_ci"

  #Workflow development variables
  FRESH_BUILD: "1"
  CLEAN_UP: "1"
  KEEP_BUILD: "1"
  DOCKER_EXEC: docker exec -t -u dev
  DEBUG_SKIP: "1"

jobs:
  build-qualcomm-bsp:
    #specify labels to run on qcom desktop
    runs-on: [self-hosted, linux, x64, qcom]
    env:
      MANI_REPO: ${{ inputs.mani_repo }}
      MANI_BRANCH: ${{ inputs.mani_branch }}
      MANI_XML: ${{ inputs.mani_xml }}
      BUILD_NAME: ${{ inputs.build_name }}
      BUILD_VER: ${{ inputs.build_version }}
      BUILD_MACHINE: ${{ inputs.build_machine }}
      BUILD_DISTRO: ${{ inputs.build_distro }}
      BUILD_IMAGE: ${{ inputs.build_image }}
      #This evaluates to [project_path]/[version]
      BUILD_PROJECT_PATH: ${{ format('{0}/{1}', inputs.build_project_path, inputs.build_version) }}
      BUILD_DOCKER: ${{ inputs.build_docker }}
      HAS_PATCHES: ${{ inputs.build_patches }}
      PATCH_SCRIPT_PATH: ${{ inputs.build_patch_script_path }}
      BUILD_RELEASE_NAME: ${{ inputs.build_release_name }}
      PYENV: ${{ inputs.PYENV }}
      QCS_SOURCES: ${{ inputs.QCS_SOURCES }}
      SKIP_STEPS: ${{ inputs.SKIP_STEPS }}

    steps:      
      - name: Set repository workspace
        #Explicit checkout into repository. Required if triggered from external repo.
        uses: actions/checkout@v5
        with:
            repository: imd-tec/qualcomm-ci
            ref: master
            ssh-key: ${{ secrets.QCI_DEPLOY_KEY }}

      - name: Extract build sources files
        if: env.DEBUG_SKIP != '1'
        run: |
          set -x

          #verify that CI_DIR is included in project path
          if grep -q "${CI_DIR}" <<< "${BUILD_PROJECT_PATH}"; then
            echo "Using project path: ${BUILD_PROJECT_PATH}"
          else
            echo "ERROR: project path ${BUILD_PROJECT_PATH} is invalid. It must be under ${CI_DIR}."
            exit 1
          fi

          #create build project directory
          mkdir -p "${BUILD_PROJECT_PATH}" && cd "${BUILD_PROJECT_PATH}"
          
          #extract optional assets (patch, cdt, etc.) if applicable
          candidates=()
          if [[ "$HAS_PATCHES" == "1" ]]; then
            candidates+=("patches.tar.gz")
          fi

          #extend to handle other assets as required
          #e.g., if [[ "$BUILD_CDT" == "1" ]]; then ...
          
          for asset in "${candidates[@]}"; do
              if [[ -f "${BUILD_PROJECT_PATH}/SOURCES/$asset" ]]; then
                echo "Extracting $asset..."
                tar -xf "${BUILD_PROJECT_PATH}/SOURCES/$asset" -C .
              fi
          done

          #extract Qualcomm source files
          tar -xf "${CI_DIR}/builds/SHARED_SOURCES/${QCS_SOURCES}.tar.gz" -C .
          
      - name: Build container and initialize user permissions & ownership
        timeout-minutes: 20
        run: |
          set -x

          #get host user and group IDs to pass to container
          export HOST_UID=$(id -u)
          export HOST_GID=$(id -g)
          
          #set image name
          IMAGE_NAME="imdt-qualcomm-ci:${BUILD_DOCKER##*:}" #append version affix from base image name
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

          #build container from dockerfile
          docker build -f "${CI_DIR}/docker/qc_ci_docker" \
          --build-arg BASE_IMAGE="${BUILD_DOCKER}" \
          -t "$IMAGE_NAME" \
          "${CI_DIR}"/scripts/docker_scripts/

          echo "=============================="
          echo -e "\n$IMAGE_NAME"
          echo -e "$PATCH_SCRIPT_PATH\n"
          echo "=============================="

          #run container
          #pass ID's to entry-point script (scripts/for_docker/docker_entry_point.sh) to setup user permissions and ownership
          docker run --rm -d \
          --name "$CONTAINER_NAME" \
          -e MANI_REPO="$MANI_REPO" \
          -e MANI_BRANCH="$MANI_BRANCH" \
          -e MANI_XML="$MANI_XML" \
          -e BUILD_IMAGE="$BUILD_IMAGE" \
          -e BUILD_RELEASE_NAME="$BUILD_RELEASE_NAME" \
          -e BUILD_VER="$BUILD_VER" \
          -e QCOM_ROOT_DIR="/home/dev/Qualcomm/${QCS_SOURCES}" \
          -e PYENV="$PYENV" \
          -e MACHINE="$BUILD_MACHINE" \
          -e DISTRO="$BUILD_DISTRO" \
          -e PATCH_SCRIPT_PATH="$PATCH_SCRIPT_PATH" \
          -v "${BUILD_PROJECT_PATH}:/home/dev/Qualcomm" \
          -v "${CI_DIR}/scripts/docker_scripts/:/home/dev/tools/" \
          "$IMAGE_NAME" "$HOST_UID" "$HOST_GID" \
          sleep infinity

          #stream entry point script logs
          docker logs -f "${CONTAINER_NAME}" &
          LOG_PID=$!

          #wait for entry script to signal completion
          until docker exec "${CONTAINER_NAME}" test -f /tmp/ready; do sleep 2; done

          #kill log stream
          kill $LOG_PID || true

          #verify that IDs are correct and ownership has been transferred correctly
          result=$($DOCKER_EXEC "${CONTAINER_NAME}" bash -lc 'id')

          if [[ $result != *"uid=$HOST_UID"* && $result != *"gid=$HOST_GID"* ]]; then
            echo "ERROR: User IDs do not match"
            exit 1
          fi

      - name: Build netrc
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
          set -xe

          #build netrc
          bash /home/dev/tools/build_netrc.sh && test -f /home/dev/.netrc
          '

      - name: Patch and synchronize repos
        if: ${{ !contains(env.SKIP_STEPS, 'sync_repos') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
          set -xe

          if [ -d "/home/dev/Qualcomm/patches" ]; then
            PATCHFILE="/home/dev/Qualcomm/patches/sync_snap_v2_remove_chipcode_copy.patch"
            TARGET="${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/sync_snap_v2.sh"
            #batch to bypass user prompts
            patch --batch "$TARGET" "$PATCHFILE" 
          fi

          #sync repos
          bash -x /home/dev/build_scripts/sync_repos.sh -u $MANI_REPO -b $MANI_BRANCH -m $MANI_XML
          '

      - name: Configure kernel directories
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
          set -ex
          bash -x /home/dev/build_scripts/setup_kernel.sh
          '

      - name: Apply IMDT patches to Qualcomm source
        if: ${{ !contains(env.SKIP_STEPS, 'apply_patches') }}
        run: | 
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
          set -ex

          #applying IMDT patches to QC source
          bash -x "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/${PATCH_SCRIPT_PATH}"
          '

      - name: Build kernel
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
          bash -x /home/dev/build_scripts/build_kernel.sh --lto "thin" --jobs 8
          '

      - name: Build HLOS
        if: ${{ !contains(env.SKIP_STEPS, 'build_hlos') }}
        run: |
          set -ex
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
          cd "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/poky"

          patch ./meta-qti-bsp/classes/populate_sdk_qti.bbclass \
          "${HOME}/Qualcomm/patches/populate_sdk_qti_remove_llvm_native.patch"
          
          cp -rn "${QCOM_ROOT_DIR}/LE.FRAMEWORK.2.0.r1/apps_proc/poky/"* \
                  "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/poky/"

          cp -rn "${QCOM_ROOT_DIR}/LE.FRAMEWORK.2.0.r1/apps_proc/src/"* \
                  "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/src/"
          '

      - name: Build image
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
          set -xe

          #set Yocto environment
          cd "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc"
          pyenv global $PYENV

          export MACHINE=$BUILD_MACHINE
          export DISTRO=$BUILD_DISTRO
          source poky/qti-conf/set_bb_env.sh

          #build image
          bitbake -k "${BUILD_IMAGE}" --runall=fetch
          bitbake -k "${BUILD_IMAGE}"
          '

      - name: Generate Yocto SDK
        if: ${{ !contains(env.SKIP_STEPS, 'build_sdk') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
          set -xe

          bitbake ${BUILD_IMAGE} -c populate_sdk
          
          #locate generated SDK script and rename
          SDK_DIR="${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/build-${BUILD_DISTRO}/tmp-glibc/deploy/sdk/"
          
          #verify that there is exactly one script matching
          mapfile -t matches < <(find "$SDK_DIR" -maxdepth 1 -type f -name "*${BUILD_DISTRO}*.sh")
          if (( ${#matches[@]} == 1 )); then
            rename it to [project_name]-sdk-v[version].sh (e.g., imsu_glasses_sdk-v1.0.0.sh)
            mv -- "${matches[0]}" "${SDK_DIR}/${BUILD_RELEASE_NAME%_prebuilt*}-sdk-v${BUILD_VER}.sh"
          else
            echo "Warning: Expected exactly 1 SDK file, found ${#matches[@]}. Skipping rename."
            exit 0
          fi
          '
      
      - name: Build non-HLOS components
        if: ${{ !contains(env.SKIP_STEPS, 'build_non_hlos') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
          set -xe
          bash -x /home/dev/build_scripts/build_non_hlos.sh --build all
          '

      - name: Create release artifact
        if: ${{ !contains(env.SKIP_STEPS, 'create_release') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
          set -xe
          FULL_RELEASE_NAME="${BUILD_RELEASE_NAME}_v${BUILD_VER}"
          RELEASE_DIR="/home/dev/Qualcomm/${FULL_RELEASE_NAME}"

          #if release artifact already exists, remove it
          [ -d "$RELEASE_DIR" ] && rm -rf "$RELEASE_DIR"
          
          #create new release artifact
          cd /home/dev/build_scripts
          python3 create_release.py \
           -r "$RELEASE_DIR" \
           -x "${QCOM_ROOT_DIR}/contents.xml" \
           -b "${QCOM_ROOT_DIR}"
          
          #create prebuilt tarball 
          tar -C "/home/dev/Qualcomm/" -czf "${FULL_RELEASE_NAME}.tar.gz" "${FULL_RELEASE_NAME}"
          
          #verify tarball creation and non-compresssed directory
          if [ -f "/home/dev/Qualcomm/${FULL_RELEASE_NAME}.tar.gz" ]; then
            echo "Release artifact created at /home/dev/Qualcomm/${FULL_RELEASE_NAME}.tar.gz"
            echo "Cleaning up temporary release directory..."
            if [ -d "$RELEASE_DIR" ]; then
              rm -rf "$RELEASE_DIR"
            fi
          else
            echo "ERROR: Release artifact creation failed."
            exit 1
          fi
          '

      - name: Clean up container and image
        if: ${{ always() && env.CLEAN_UP == '1' }}
        run: |
          chmod +x $GITHUB_WORKSPACE/scripts/stop-container.sh
          bash $GITHUB_WORKSPACE/scripts/stop-container.sh ${CONTAINER_NAME} ${IMAGE_NAME}

      - name: Clean up source files
        if:  ${{ always() && env.CLEAN_UP == '1' }}
        run: |
          set -euo pipefail -x
          [ -d "${BUILD_PROJECT_PATH:?}/qcs8550-le-1-0_amss_standard_oem_apqgps" ] && \
          rm -rf "${BUILD_PROJECT_PATH:?}/qcs8550-le-1-0_amss_standard_oem_apqgps"

          if [ $HAS_PATCHES == 1 ]; then
            [ -d "${BUILD_PROJECT_PATH:?}/patches" ] && \
              rm -rf "${BUILD_PROJECT_PATH:?}/patches"
          fi            



         