name: Build qc bsp v1.0.0 public

defaults:
  run:
    shell: bash -eo pipefail {0}

env:
  #Build variables
  CONTAINER_NAME: "ci_qualcomm_${{ github.run_id }}"
  CI_DIR: "/mnt/nvme1/qcom_ci"
  DOCKER_VER: "0.5.1"

  SRC_REPO: "qcs8550-le-1-0_amss_standard_oem_apqgps"
  MANI_REPO: "https://github.com/imd-tec/imdt-qcom-manifest.git"
  MANI_BRANCH: "kirkstone"
  MANI_XML: "default.xml" 
  BUILD_VER: "1.0.0"
  
  BUILD_SDK: "1"
  BUILD_CDT: "0"

  PYENV: "3.8.16"
  MACHINE: "imdt-qcs8550-sbc"
  DISTRO: "imdt-qcom-distro-debug"

  
  #Development variables
  FRESH_BUILD: "1"
  CLEAN_UP: "1"
  KEEP_BUILD: "1"
  DOCKER_EXEC: docker exec -t -u dev 

on:
  push:
    branches:
      - master

  #workflow is executed every night at 9
  workflow_dispatch:
  # schedule:
    # - cron: '0 21 * * *'
  
jobs:
  build-qualcomm-bsp:
    #specify labels to run on qcom desktop
    runs-on: [self-hosted, linux, x64, qcom-ci]

    steps:
      - name: Show trigger info
        run: |
          echo "Triggered by ${{ github.event_name }} event."
          echo "Branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Extract fresh source files
        if: env.FRESH_BUILD == '1'
        run: |
          set -ex
          cd ${CI_DIR}/builds/${BUILD_VER}
          tar -xf sources/patches.tar.gz -C ${CI_DIR}/builds/${BUILD_VER}
          tar -xf "sources/${SRC_REPO}.tar.gz" -C ${CI_DIR}/builds/${BUILD_VER}
          test -d "${SRC_REPO}" && test -d patches
          
      - name: Build container and initialize user permissions/ownership
        timeout-minutes: 3
        run: |
          set +x
          export HOST_UID=$(id -u)
          export HOST_GID=$(id -g)

          docker build -f "${CI_DIR}/docker/qc_ci_docker" \
          -t imdt-qualcomm-ci:"${DOCKER_VER}" \
          "${CI_DIR}/actions-runner/_work/qualcomm-ci/qualcomm-ci/for_docker"

          docker run --rm -d \
          --name "$CONTAINER_NAME" \
          -e SRC_REPO="$SRC_REPO" \
          -e MANI_REPO="$MANI_REPO" \
          -e MANI_BRANCH="$MANI_BRANCH" \
          -e MANI_XML="$MANI_XML" \
          -e QCOM_ROOT_DIR="/home/dev/Qualcomm/${SRC_REPO}" \
          -e MACHINE="$MACHINE" -e DISTRO="$DISTRO" -e PYENV="$PYENV" \
          -v "${PWD}/for_docker:/workflows" \
          -v "${CI_DIR}/builds/${BUILD_VER}:/home/dev/Qualcomm" \
          -v "${CI_DIR}/scripts/:/home/dev/tools/" \
          imdt-qualcomm-ci:${DOCKER_VER} $HOST_UID $HOST_GID \
          sleep infinity

          #stream entry point script logs
          docker logs -f "${CONTAINER_NAME}" &
          LOG_PID=$!

          #wait for entry script to signal completion
          until docker exec "${CONTAINER_NAME}" test -f /tmp/ready; do sleep 2; done

          #kill log stream
          kill $LOG_PID || true

          #verify that IDs are correct and ownership has been transferred correctly
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc 'ls -la; id; env'

      - name: Build netrc
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
          set -ex
          #build netrc
          bash /home/dev/tools/build_netrc.sh;
          test -f /home/dev/.netrc
          '
        
      - name: Patch and synchronize repos
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
          set -ex
          #apply patches to target
          PATCHFILE="/home/dev/Qualcomm/patches/sync_snap_v2_remove_chipcode_copy.patch" 
          TARGET="${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/sync_snap_v2.sh"
          #batch to bypass user prompts
          patch --batch "$TARGET" "$PATCHFILE" 
          #sync repos
          bash -x /home/dev/build_scripts/sync_repos.sh -u $MANI_REPO -b $MANI_BRANCH -m $MANI_XML
          '

      - name: Configure kernel directories
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
          set -ex
          bash -x /home/dev/build_scripts/setup_kernel.sh
          '

      - name: Apply IMDT patches to Qualcomm source
        run: | 
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
          set -ex
          #applying IMDT patches to QC source
          cd "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc"
          bash -x ./imdt-patch-qcs8550-build.sh
          '

      - name: Build kernel
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
          bash -x /home/dev/build_scripts/build_kernel.sh --lto "thin" --jobs 8
          '

      - name: Build HLOS
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
          cd "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/poky"
          patch ./meta-qti-bsp/classes/populate_sdk_qti.bbclass \
          "${HOME}/Qualcomm/patches/populate_sdk_qti_remove_llvm_native.patch"
          cp -rn "${QCOM_ROOT_DIR}/LE.FRAMEWORK.2.0.r1/apps_proc/poky/"* "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/poky/"
          cp -rn "${QCOM_ROOT_DIR}/LE.FRAMEWORK.2.0.r1/apps_proc/src/"* "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/src/"
          '

      - name: Build image
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
          #setup yocto env
          cd "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc"
          pyenv global $PYENV
          source poky/qti-conf/set_bb_env.sh
          #build image
          bitbake -k imdt-image-weston --runall=fetch
          bitbake -k imdt-image-weston
          '

      - name: Generate Yocto SDK
        if: env.BUILD_SDK == '1'
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
          #setup yocto env
          cd "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc"
          pyenv global $PYENV
          source poky/qti-conf/set_bb_env.sh
          bitbake imdt-image-weston -c populate_sdk
          '

      - name: Build non-HLOS components
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
          bash -x /home/dev/build_scripts/build_non_hlos.sh --build all 
          '

      # - name: Generate CDT
      #   if: env.BUILD_CDT == '1'
      #   run: |

      - name: Create release image
        if: ${{ env.KEEP_BUILD == '1' }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
          cd /home/dev/build_scripts
          python3 create_release.py -r "/home/dev/Qualcomm/${BUILD_VER}/RELEASE/" -x "/home/dev/Qualcomm/${BUILD_VER}/${SRC_REPO}/contents.xml" -b "/home/dev/Qualcomm/${BUILD_VER}/${SRC_REPO}/"
          '

      - name: Clean up source files
        if:  ${{ always() && env.CLEAN_UP == '1' }}
        run: |
          set -euo pipefail -x
          [ -d "/mnt/nvme1/qcom_ci/builds/${BUILD_VER:?}/qcs8550-le-1-0_amss_standard_oem_apqgps" ] && \
          rm -rf "/mnt/nvme1/qcom_ci/builds/${BUILD_VER:?}/qcs8550-le-1-0_amss_standard_oem_apqgps"
          [ -d "/mnt/nvme1/qcom_ci/builds/${BUILD_VER:?}/patches" ] && \
            rm -rf "/mnt/nvme1/qcom_ci/builds/${BUILD_VER:?}/patches"
          
      - name: Clean up container and image
        if: ${{ always()}}
        run: |
          chmod +x ./stop-container.sh
          ./stop-container.sh ${CONTAINER_NAME} ${DOCKER_VER}
      
