#Reusable workflow triggerd by workflow_call from external manifest repo
name: Build qcom BSP (reusable)

defaults:
  run:
    shell: bash -eo pipefail {0}

on:
    workflow_call:
        inputs:
          mani_repo:
            required: true
            description: Manifest repository URL
            type: string            

          mani_branch:
            required: true
            description: Branch of manifest repository
            type: string   

          mani_xml:
            required: true
            description: Path to the manifest XML file
            type: string

          build_name:
            required: true
            description: Name of the build
            type: string

          build_version:
            required: true
            description: Version of the manifest
            type: string     

          build_machine:
            required: true
            description: Build machine
            type: string      

          build_distro:
            required: true
            description: Build distro
            type: string      
                  
          build_image:
            required: true
            description: Build image
            type: string      

          build_project_path:
            required: true
            description: Local path on runner to project directory
            type: string       

          build_docker:
            required: true
            description: Docker image to use
            type: string

          build_cdt:
            required: true
            type: string        

          build_patches:
            required: true
            description: Whether the build has patches
            type: string

          build_release_name:
            required: true
            description: Release artifact name
            type: string     

    workflow_dispatch:

env:
  #Build constants
  CONTAINER_NAME: "ci_qualcomm_${{ github.run_id }}"
  CI_DIR: "/mnt/nvme1/qcom_ci"
  QCS_SOURCES: "qcs8550-le-1-0_amss_standard_oem_apqgps"
  PYENV: "3.8.16"

  #Workflow development variables  
  BUILD_SDK: "1"
  BUILD_CDT: "0"
  FRESH_BUILD: "1"
  CLEAN_UP: "1"
  KEEP_BUILD: "1"
  DOCKER_EXEC: docker exec -t -u dev 

jobs:
  build-qualcomm-bsp:
    #specify labels to run on qcom desktop
    runs-on: [self-hosted, linux, x64, qcom]
    steps:      
      - name: Set repository workspace
        #Explicit checkout into repository. Required if triggered from external repo.
        uses: actions/checkout@v5
        with:
            repository: imd-tec/qualcomm-ci
            ref: master
            ssh-key: ${{ secrets.QCI_DEPLOY_KEY }}

      - name: Set key build variables
        run: |
          #set workflow_call inputs to shell vars
          MANI_REPO='${{ inputs.mani_repo }}'
          MANI_BRANCH='${{ inputs.mani_branch }}'
          MANI_XML='${{ inputs.mani_xml }}'
          BUILD_NAME='${{ inputs.build_name }}'
          BUILD_VER='${{ inputs.build_version }}'
          BUILD_MACHINE='${{ inputs.build_machine }}'
          BUILD_DISTRO='${{ inputs.build_distro }}'
          BUILD_IMAGE='${{ inputs.build_image }}'
          BUILD_PROJECT_PATH='${{ inputs.build_project_path }}/${{ inputs.build_version }}'
          BUILD_DOCKER='${{ inputs.build_docker }}'
          BUILD_CDT='${{ inputs.build_cdt }}'
          HAS_PATCHES='${{ inputs.build_patches }}'
          BUILD_RELEASE_NAME='${{ inputs.build_release_name }}'


          echo "Build Manifest:"
          echo "Repository: $MANI_REPO"
          echo "Branch: $MANI_BRANCH" 
          echo "Manifest: $MANI_XML"
          echo "Name: $BUILD_NAME"
          echo "Version: $BUILD_VER"
          echo "Machine: $BUILD_MACHINE"
          echo "Distro: $BUILD_DISTRO"
          echo "Image: $BUILD_IMAGE"
          echo "Build Path: $BUILD_PROJECT_PATH"
          echo "Docker: $BUILD_DOCKER"
          echo "CDT: $BUILD_CDT"
          echo "Has Patches: $HAS_PATCHES"
          echo "Release Name: $BUILD_RELEASE_NAME"
          echo ""

          #export variables to environment for use in subsequent steps
          {
            echo "MANI_REPO=$MANI_REPO"
            echo "MANI_BRANCH=$MANI_BRANCH"
            echo "MANI_XML=$MANI_XML"
            echo "BUILD_NAME=$BUILD_NAME"
            echo "BUILD_VER=$BUILD_VER"
            echo "BUILD_MACHINE=$BUILD_MACHINE"
            echo "BUILD_DISTRO=$BUILD_DISTRO"
            echo "BUILD_IMAGE=$BUILD_IMAGE"
            echo "BUILD_PROJECT_PATH=$BUILD_PROJECT_PATH"
            echo "BUILD_DOCKER=$BUILD_DOCKER"
            echo "BUILD_CDT=$BUILD_CDT"
            echo "HAS_PATCHES=$HAS_PATCHES"
            echo "BUILD_RELEASE_NAME=$BUILD_RELEASE_NAME"
          } >> "$GITHUB_ENV"

      - name: Extract build sources files
        if: ${{ env.FRESH_BUILD == '1' && inputs.build_name != 'development' }}
        run: |
          set -x

          #verify that CI_DIR is included in project path
          if grep -q "${CI_DIR}" <<< "${BUILD_PROJECT_PATH}"; then
            echo "Using project path: ${BUILD_PROJECT_PATH}"
          else
            echo "ERROR: project path ${BUILD_PROJECT_PATH} is invalid. It must be under ${CI_DIR}."
            exit 1
          fi

          #create build project directory
          mkdir -p "${BUILD_PROJECT_PATH}" && cd "${BUILD_PROJECT_PATH}"

          #extract patches if applicable, warn if not present
          if [ $HAS_PATCHES == 1 ]; then
            if [ -f "${BUILD_PROJECT_PATH}/SOURCES/patches/patches.tar.gz" ]; then
            echo "Applying patches for build..."
            tar -xf "${BUILD_PROJECT_PATH}/SOURCES/patches/patches.tar.gz" -C .
            else
              echo "::warning expected patches not found in ${BUILD_PROJECT_PATH}/SOURCES/patches/patches.tar.gz. Continuing..."
            fi
          fi
          
          #extract Qualcomm source files
          tar -xf "${CI_DIR}/builds/SHARED_SOURCES/${QCS_SOURCES}.tar.gz" -C .
          
      - name: Build container and initialize user permissions & ownership
        run: |
          set +x
          #get host user and group IDs to pass to container
          export HOST_UID=$(id -u)
          export HOST_GID=$(id -g)
          
          
          DOCKER_NAME="imdt-qualcomm-ci:${BUILD_DOCKER##*:}"

          #build container from dockerfile
          docker build -f "${CI_DIR}/docker/qc_ci_docker" \
          --build-arg BASE_IMAGE="${BUILD_DOCKER}" \
          -t $DOCKER_NAME \
          for_docker

          #run container
          #pass ID's to entry-point script (scripts/for_docker/docker_entry_point.sh) to setup user permissions and ownership
          docker run --rm -d \
          --name "$CONTAINER_NAME" \
          -e MANI_REPO="$MANI_REPO" \
          -e MANI_BRANCH="$MANI_BRANCH" \
          -e MANI_XML="$MANI_XML" \
          -e BUILD_RELEASE_NAME="$BUILD_RELEASE_NAME" \
          -e QCOM_ROOT_DIR="/home/dev/Qualcomm/${QCS_SOURCES}" \
          -e MACHINE="$BUILD_MACHINE" -e DISTRO="$BUILD_DISTRO" -e PYENV="$PYENV" \
          -v "${PWD}/for_docker:/workflows" \
          -v "${BUILD_PROJECT_PATH}:/home/dev/Qualcomm" \
          -v "${CI_DIR}/scripts/:/home/dev/tools/" \
          $DOCKER_NAME $HOST_UID $HOST_GID \
          sleep infinity

          #stream entry point script logs
          docker logs -f "${CONTAINER_NAME}" &
          LOG_PID=$!

          #wait for entry script to signal completion
          until docker exec "${CONTAINER_NAME}" test -f /tmp/ready; do sleep 2; done

          #kill log stream
          kill $LOG_PID || true

          #verify that IDs are correct and ownership has been transferred correctly
          result=$($DOCKER_EXEC "${CONTAINER_NAME}" bash -lc 'id')

          if [[ $result != *"uid=$HOST_UID"* && $result != *"gid=$HOST_GID"* ]]; then
            echo "ERROR: User IDs do not match"
            exit 1
          fi
      # - name: Build netrc
      #   run: |
      #     $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
      #     set -ex
      #     #build netrc
      #     bash /home/dev/tools/build_netrc.sh;
      #     test -f /home/dev/.netrc
      #     '

      # - name: Patch and synchronize repos
      #   run: |
      #     $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
      #     set -ex
      #     #apply patches to target
      #     PATCHFILE="/home/dev/Qualcomm/patches/sync_snap_v2_remove_chipcode_copy.patch" 
      #     TARGET="${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/sync_snap_v2.sh"
      #     #batch to bypass user prompts
      #     patch --batch "$TARGET" "$PATCHFILE" 
      #     #sync repos
      #     bash -x /home/dev/build_scripts/sync_repos.sh -u $MANI_REPO -b $MANI_BRANCH -m $MANI_XML
      #     '

      # - name: Configure kernel directories
      #   run: |
      #     $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
      #     set -ex
      #     bash -x /home/dev/build_scripts/setup_kernel.sh
      #     '

      # - name: Apply IMDT patches to Qualcomm source
      #   run: | 
      #     $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
      #     set -ex
      #     #applying IMDT patches to QC source
      #     cd "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc"
      #     bash -x ./imdt-patch-qcs8550-build.sh
      #     '

      # - name: Build kernel
      #   run: |
      #     $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
      #     bash -x /home/dev/build_scripts/build_kernel.sh --lto "thin" --jobs 8
      #     '

      # - name: Build HLOS
      #   run: |
      #     $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
      #     cd "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/poky"
      #     patch ./meta-qti-bsp/classes/populate_sdk_qti.bbclass \
      #     "${HOME}/Qualcomm/patches/populate_sdk_qti_remove_llvm_native.patch"
      #     cp -rn "${QCOM_ROOT_DIR}/LE.FRAMEWORK.2.0.r1/apps_proc/poky/"* "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/poky/"
      #     cp -rn "${QCOM_ROOT_DIR}/LE.FRAMEWORK.2.0.r1/apps_proc/src/"* "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/src/"
      #     '

      # - name: Build image
      #   run: |
      #     $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
      #     #setup yocto env
      #     cd "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc"
      #     pyenv global $PYENV
      #     source poky/qti-conf/set_bb_env.sh
      #     #build image
      #     bitbake -k imdt-image-weston --runall=fetch
      #     bitbake -k imdt-image-weston
      #     '

      # - name: Generate Yocto SDK
      #   if: env.BUILD_SDK == '1'
      #   run: |
      #     $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
      #     #setup yocto env
      #     cd "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc"
      #     pyenv global $PYENV
      #     source poky/qti-conf/set_bb_env.sh
      #     bitbake imdt-image-weston -c populate_sdk
      #     '

      # - name: Build non-HLOS components
      #   run: |
      #     $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
      #     bash -x /home/dev/build_scripts/build_non_hlos.sh --build all 
      #     '

      # # - name: Generate CDT
      # #   if: env.BUILD_CDT == '1'
      # #   run: |

      # - name: Create release artifact
      #   if: ${{ env.KEEP_BUILD == '1' }}
      #   run: |
      #     $DOCKER_EXEC "${CONTAINER_NAME}" bash -lc '
      #     release_dir="/home/dev/Qualcomm/RELEASE/${BUILD_RELEASE_NAME:?}"

      #     #if release artifact already exists, remove it
      #     [ -d "$release_dir" ] && rm -rf "$release_dir"
          
      #     #create new release artifact
      #     cd /home/dev/build_scripts
      #     python3 create_release.py \
      #      -r "$release_dir" \
      #      -x "${QCOM_ROOT_DIR}/contents.xml" \
      #      -b "${QCOM_ROOT_DIR}"
      #     '

      - name: Clean up source files
        if:  ${{ always() && env.CLEAN_UP == '1' }}
        run: |
          set -euo pipefail -x
          [ -d "${BUILD_PROJECT_PATH:?}/qcs8550-le-1-0_amss_standard_oem_apqgps" ] && \
          rm -rf "${BUILD_PROJECT_PATH:?}/qcs8550-le-1-0_amss_standard_oem_apqgps"

          if [ $HAS_PATCHES == 1 ]; then
            [ -d "${BUILD_PROJECT_PATH:?}/SOURCES/patches" ] && \
              rm -rf "${BUILD_PROJECT_PATH:?}/SOURCES/patches"
          fi            
      - name: Clean up container and image
        if: ${{ always() }}
        run: |
          chmod +x ./stop-container.sh
          ./stop-container.sh ${CONTAINER_NAME} ${DOCKER_VER}



         