#Reusable workflow triggerd by workflow_call from external manifest repo
name: Build IMDT QCOM BSP 

defaults:
  run:
    shell: bash -ueo pipefail {0}

on:
  #only triggered on external workflow call
  workflow_call:
      inputs:
        MANIFEST_REPOSITORY:
          required: true
          description: Manifest repository URL
          type: string            

        MANIFEST_BRANCH:
          required: true
          description: Branch of manifest in repository
          type: string   

        MANIFEST_XML:
          required: true
          description: Path to the manifest XML file in branch 
          type: string

        BUILD_NAME:
          required: true
          description: Name of the build (e.g. imsu_glasses_bsp-v1.0.0)
          type: string
        
        BUILD_VERSION:
          required: true
          description: Version of the manifest (e.g. 1.0.0)
          type: string     

        BUILD_KERNEL_VARIANT:
          required: true
          description: Kernel variant to use (e.g. gki-kernel)
          type: string

        BUILD_MACHINE:
          required: true
          description: Target hardware machine (e.g. imdt-qcs8550-sbc)
          type: string      

        BUILD_DISTRO:
          required: true
          description: Build distribution (e.g. imdt-distro-debug)
          type: string

        BUILD_IMAGE:
          required: true
          description: Target image to build (e.g. imdt-image-weston)
          type: string      

        BASE_DOCKER_IMAGE:
          required: true
          description: Docker base image to use (e.g. imdtec/imdt-qualcomm-build-setup:0.5.1)
          type: string

        IMDT_PATCH_SCRIPT_PATH:
          required: true
          description: Path to IMDT patch build script (e.g. LE.PRODUCT.2.1.r1/apps_proc/imdt-patch-qcs8550-build.sh)
          type: string

        BUILD_RELEASE_NAME:
          required: true
          description: Release artifact name (e.g. imsu_glasses_prebuilt_release)
          type: string     
        
        PYENV:
          required: true
          description: Python environment version to use (e.g. 3.8.16)
          type: string
          default: "3.8.16"

        QCS_SOURCES:
          required: true
          description: Qualcomm source files to use (e.g. qcs8550-le-1-0_amss_standard_oem_apqgps-r00087.1)
          type: string

        SKIP_STEPS:
          required: false
          description: Build steps to skip, defined by 'contains' conditionals below (e.g. [sync_repos, build_hlos])
          type: string

        DEV_STATE_LOG:
          required: false
          description: Development build details for logging purposes (see $CI_DEV_DIR/state)
          type: string

        BUILD_SWU:
          required: false
          description: Generate SWUpdate update image
          type: boolean
          default: false
          
        PRESERVE_BUILD_DIR:
          required: false
          description: Preserve build files after build completion
          type: boolean
          default: false

        PRESERVE_DOCKER:
          required: false
          description: Whether to preserve docker container and image after build completion
          type: boolean
          default: false

        JOB_TIMEOUT:
          required: false
          description: Timeout for the build job in minutes 
          type: number
          default: 720 # 12 hours

env:
  CONTAINER_NAME: "ci_qualcomm_${{ github.run_id }}"
  DOCKER_EXEC: docker exec -t -u dev
  
jobs:
  build-qualcomm-bsp:
    #specify labels to run on qcom desktop
    runs-on: [self-hosted, linux, x64, qcom]
    timeout-minutes: ${{ inputs.JOB_TIMEOUT }}
    env:
      MANIFEST_REPOSITORY: ${{ inputs.MANIFEST_REPOSITORY }}
      MANIFEST_BRANCH: ${{ inputs.MANIFEST_BRANCH }}
      MANIFEST_XML: ${{ inputs.MANIFEST_XML }}
      BUILD_NAME: ${{ inputs.BUILD_NAME }}
      BUILD_VERSION: ${{ inputs.BUILD_VERSION }}
      KERNEL_VARIANT: ${{ inputs.BUILD_KERNEL_VARIANT }}
      MACHINE: ${{ inputs.BUILD_MACHINE }}
      DISTRO: ${{ inputs.BUILD_DISTRO }}
      IMAGE: ${{ inputs.BUILD_IMAGE }}
      BASE_DOCKER_IMAGE: ${{ inputs.BASE_DOCKER_IMAGE }}
      IMDT_PATCH_SCRIPT_PATH: ${{ inputs.IMDT_PATCH_SCRIPT_PATH }}
      RELEASE_NAME: ${{ inputs.BUILD_RELEASE_NAME }}
      PYENV: ${{ inputs.PYENV }}
      QCS_SOURCES: ${{ inputs.QCS_SOURCES }}
      SKIP_STEPS: ${{ inputs.SKIP_STEPS }}
      DEV_STATE_LOG: ${{ inputs.DEV_STATE_LOG }}

    steps:      
      - name: Set repository workspace
        #explicitly checkout into the CI repository. Required if triggered from external repo.
        uses: actions/checkout@v6
        with:
            repository: imd-tec/qualcomm-ci
            ref: stable
            token: ${{ secrets.QCI_DEPLOY_PAT }}
            persist-credentials: false
            path: qualcomm_ci
          
      - name: Verify service environment variables
        run: |
          ERROR="ERROR: Service variable/s not set. Daemon reload and service restart required?"
          echo "CI_DIR: ${CI_DIR:?${ERROR}}"
          echo "CI_DEV_DIR: ${CI_DEV_DIR:?${ERROR}}"
          echo "BSP_SOURCES_DIR: ${BSP_SOURCES_DIR:?${ERROR}}"
          echo "DL_DIR: ${DL_DIR:?${ERROR}}"
          echo "SSTATE_DIR: ${SSTATE_DIR:?${ERROR}}"

      - name: Create build project directory
        run: | 
          #set build project path
          BUILD_PROJECT_DIR="${CI_DIR}/builds/${BUILD_NAME}"

          #export to GITHUB_ENV for later steps
          echo "BUILD_PROJECT_DIR=${BUILD_PROJECT_DIR}" >> $GITHUB_ENV

          #create and change to build project directory
          echo "Using project path: ${BUILD_PROJECT_DIR}"
          mkdir -p "${BUILD_PROJECT_DIR}" && cd "${BUILD_PROJECT_DIR}"

      - name: Extract build sources files into build directory
        if: ${{ !contains(env.SKIP_STEPS, 'extract_sources') }}
        working-directory: ${{ github.workspace }}/qualcomm_ci/scripts
        run: bash extract-sources.sh
 
      - name: Create Docker image, build container and initialize user permissions & ownership
        working-directory: ${{ github.workspace }}/qualcomm_ci/scripts
        run: bash create-docker-build-env.sh

      - name: Patch and synchronize repos
        if: ${{ !contains(env.SKIP_STEPS, 'sync_repos') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          if [ -d "/home/dev/Qualcomm/patches" ]; then
            PATCHFILE="/home/dev/Qualcomm/patches/sync_snap_v2_remove_chipcode_copy.patch"
            TARGET="${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/sync_snap_v2.sh"
            #batch to bypass user prompts
            patch --batch "$TARGET" "$PATCHFILE" 
          fi

          #sync repos
          bash /home/dev/build_scripts/sync_repos.sh -u "$MANIFEST_REPOSITORY" -b "$MANIFEST_BRANCH" -m "$MANIFEST_XML" '

      - name: Configure kernel directories
        if: ${{ !contains(env.SKIP_STEPS, 'conf_kernel') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          bash /home/dev/build_scripts/setup_kernel.sh '

      - name: Apply IMDT patches to Qualcomm source
        if: ${{ !contains(env.SKIP_STEPS, 'apply_patches') }}
        run: | 
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          bash "${QCOM_ROOT_DIR}/${IMDT_PATCH_SCRIPT_PATH}" '
      
      - name: Configure contents.xml
        if: ${{ !contains(env.SKIP_STEPS, 'conf_contents') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          python3 /home/dev/build_scripts/configure_contents_xml.py -d "${DISTRO}" -m "${MACHINE}" -i "${IMAGE}" -x "${QCOM_ROOT_DIR}/contents.xml" ' 

      - name: Build kernel
        if: ${{ !contains(env.SKIP_STEPS, 'build_kernel') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          bash /home/dev/build_scripts/build_kernel.sh \
          --lto "thin" --jobs 8 \
          --build_variant "${KERNEL_VARIANT}" \
          --build_output_dir "../out/msm-kernel-kalama_le-${KERNEL_VARIANT}" '
      
      - name: Copy additional HLOS files
        if: ${{ !contains(env.SKIP_STEPS, 'copy_hlos_files') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          cd "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/poky"
          cp -rn "${QCOM_ROOT_DIR}/LE.FRAMEWORK.2.0.r1/apps_proc/poky/"* \
                  "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/poky/"

          cp -rn "${QCOM_ROOT_DIR}/LE.FRAMEWORK.2.0.r1/apps_proc/src/"* \
                  "${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/src/" '

      - name: Bitbake fetch sources
        if: ${{ !contains(env.SKIP_STEPS, 'bitbake_fetch') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          #set Yocto environment
          source /home/dev/tools/container_scripts/setup-yocto-environment.sh
          bitbake "${IMAGE}" --runall=fetch '

      - name: Bitbake build image
        if: ${{ !contains(env.SKIP_STEPS, 'bitbake_build') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          #set Yocto environment
          source /home/dev/tools/container_scripts/setup-yocto-environment.sh
          
          #build image
          bitbake "${IMAGE}" '

      - name: Build non-HLOS components
        id: build_non_hlos
        if: ${{ !contains(env.SKIP_STEPS, 'build_non_hlos') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          bash /home/dev/build_scripts/build_non_hlos.sh --build all '

      - name: Generate SWUpdate image
        if: ${{ inputs.BUILD_SWU }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          bash /home/dev/tools/container_scripts/generate-swu.sh'

      - name: Generate Yocto SDK
        if: ${{ !contains(env.SKIP_STEPS, 'build_sdk') }}
        continue-on-error: true
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          bash /home/dev/tools/container_scripts/generate-sdk.sh '

      - name: Create release artifact
        if: ${{ !contains(env.SKIP_STEPS, 'create_release') }}
        run: |
          $DOCKER_EXEC "${CONTAINER_NAME}" bash -c '
          bash /home/dev/tools/container_scripts/create-artifact.sh '

      - name: Update development build state logs
        if: ${{ always() && env.BUILD_VERSION == 'development' }}
        working-directory: ${{ github.workspace }}/qualcomm_ci/scripts
        env: 
          STATUS: ${{ job.status }}
        run: |
          echo "Build status: ${STATUS}"
          echo "Development repository states: ${DEV_STATE_LOG}"
          bash log-dev-state.sh "${STATUS}" "${DEV_STATE_LOG}" "${MANIFEST_REPOSITORY}" "${MANIFEST_XML}"
          
      - name: Clean up container and image
        if: ${{ always() && !inputs.PRESERVE_DOCKER }}
        working-directory: ${{ github.workspace }}/qualcomm_ci/scripts
        run: |
          docker compose \
          -f "${GITHUB_WORKSPACE}"/qualcomm_ci/docker/docker-compose.yaml \
          down --rmi local

      - name: Preserve source files
        if: ${{ always() && inputs.PRESERVE_BUILD_DIR }}
        working-directory: ${{ github.workspace }}/qualcomm_ci/scripts
        env:
          STATUS: ${{ job.status }}
          RUN_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          BRANCH: ${{ github.ref_name }}
          ACTOR: ${{ github.actor }}
        run: bash preserve-build.sh "${STATUS}" "${RUN_URL}" "${BRANCH}" "${ACTOR}"           
          
      - name: Clean up source files
        if:  ${{ always() && !inputs.PRESERVE_BUILD_DIR }}
        run: |
          set -euo pipefail -x
          echo "Cleaning up build source files..."

          if [ -d "${BUILD_PROJECT_DIR:?}/${QCS_SOURCES}" ]; then           
            rm -rf "${BUILD_PROJECT_DIR:?}/${QCS_SOURCES}"
          fi

          if [ -d "${BUILD_PROJECT_DIR:?}/patches" ]; then
            rm -rf "${BUILD_PROJECT_DIR:?}/patches"  
          fi
