name: Build qc bsp v1.0.0 public (modular)

defaults:
  run:
    shell: bash -eo pipefail {0}

env:
  CONTAINER_NAME: "ci_qualcomm_${{ github.run_id }}"
  DOCKER_VER: "0.5.1"
  SRC_REPO: "qcs8550-le-1-0_amss_standard_oem_apqgps"
  MANI_REPO: "https://github.com/imd-tec/imdt-qcom-manifest.git"
  MANI_BRANCH: "kirkstone"
  MANI_XML: "default.xml" 
  BUILD_VER: "1.0.0"
  CI_DIR: "/mnt/nvme1/qcom_ci/"
  BUILD_SDK: "1"
  BUILD_CDT: "0"
  FRESH_BUILD: "false"

on:
  push:
    branches:
      - master

  #workflow is executed every night at 9
  workflow_dispatch:
  # schedule:
    # - cron: '0 21 * * *'
  
jobs:
  build-qualcomm-bsp:
    #specify labels to run on qcom desktop
    runs-on: [self-hosted, linux, x64, qcom-ci]

    steps:
      - name: Show trigger info
        run: |
          echo "Triggered by ${{ github.event_name }} event."
          echo "Branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Extract fresh source files
        if: env.FRESH_BUILD == 'true'
        run: |
          set -x
          cd ${{ github.workspace }}
          tar -xf "${CI_DIR}/builds/patches.tar.gz" -C .
          tar -xf "${CI_DIR}/builds/${SRC_REPO}.tar.gz" -C . 
          
      - name: Run & intialize Qualcomm container (Container, permissions, netrc)
        timeout-minutes: 3
        run: |
          set -euo pipefail
          export HOST_UID=$(id -u)
          export HOST_GID=$(id -g)

          docker build -f "$CI_DIR/docker/qc_ci_docker" \
          -t imdt-qualcomm-ci:"$DOCKER_VER" \
          "$CI_DIR/actions-runner/_work/qualcomm-ci/qualcomm-ci/for_docker"

          docker run --rm -d \
          --name "$CONTAINER_NAME" \
          -e SRC_REPO="$SRC_REPO" \
          -e MANI_REPO="$MANI_REPO" \
          -e MANI_BRANCH="$MANI_BRANCH" \
          -e MANI_XML="$MANI_XML" \
          -v "$PWD/for_docker:/workflows" \
          -v "$CI_DIR/builds/:/home/dev/Qualcomm" \
          -v "$CI_DIR/scripts/:/home/dev/tools/" \
          imdt-qualcomm-ci:$DOCKER_VER $HOST_UID $HOST_GID \
          sleep infinity

          #stream entry point script logs
          docker logs -f "$CONTAINER_NAME" &
          LOG_PID=$!

          #wait for entry script to signal completion
          until docker exec "${CONTAINER_NAME}" test -f /tmp/ready; do sleep 2; done

          #kill log stream
          kill $LOG_PID || true

          #verify that IDs are correct and ownership has been transferred correctly
          docker exec -t -u dev  "$CONTAINER_NAME" bash -l -c "ls -la; id"

      - name: Patch and synchronize repos
        run: |
          #build netrc
          bash /home/dev/tools/build_netrc.sh
          tail -n 5 /home/dev/.netrc

          #extract patches
          tar -xf /home/dev/Qualcomm/patches.tar.gz -C /home/dev/Qualcomm/

          #apply patches to target
          PATCHFILE="/home/dev/Qualcomm/patches/sync_snap_v2_remove_chipcode_copy.patch" 
          TARGET="${QCOM_ROOT_DIR}/LE.PRODUCT.2.1.r1/apps_proc/sync_snap_v2.sh"
          patch --batch "$TARGET" "$PATCHFILE" 

          #sync repos
          bash -x /home/dev/build_scripts/sync_repos.sh -u $MANI_REPO -b $MANI_BRANCH -m $MANI_XML


      # - name: Configure kernel directories
      #   run: |

      # - name: Apply IMDT patches to Qualcomm source
      #   run: |

      # - name: Build kernel
      #   run: |

      # - name: Build HLOS
      #   run: |

      # - name: Build image
      #   run: |

      # - name: Generate Yocto SDK
      #   env.BUILD_SDK == '0'
      #   run: |

      # - name: Build non-HLOS components
      #   run: |

      # - name: Generate CDT
      #   env.BUILD_CDT == '0'
      #   run: |

      - name: Clean up sources
        if: env.FRESH_BUILD == 'true'
        run: |
          if [ "$FRESH_BUILD" == "true" ]; then
          set -euo pipefail -x
          [ -d "/mnt/nvme1/qcom_ci/builds/qcs8550-le-1-0_amss_standard_oem_apqgps" ] && \
          rm -rf "/mnt/nvme1/qcom_ci/builds/qcs8550-le-1-0_amss_standard_oem_apqgps"
          [ -d "/mnt/nvme1/qcom_ci/builds/patches" ] && \
            rm -rf "/mnt/nvme1/qcom_ci/builds/patches"
          fi
          
      - name: Clean up container and image
        if: always()
        run: |
          chmod +x ./stop-container.sh
          ./stop-container.sh $CONTAINER_NAME $DOCKER_VER
      
