name: Execute test cases

defaults:
  run:
    shell: bash -eo pipefail {0}

env:
  TEST_PLAN: "qc_bsp_v1.0.0_test_case.yml"

on:
  # push:
  #   branches:
  #     - master

  workflow_dispatch:
  
jobs:
  build-qualcomm-bsp:
    runs-on: [self-hosted, linux, x64, qcom-ci]

    steps:
      - name: Show trigger info
        run: |
          echo "Triggered by ${{ github.event_name }} event."
          echo "Branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Checkout repository code
        uses: actions/checkout@v4

      #PREREQUISITES
      #UART, USB AND ETH CONNECTION TO RUNNER 
      
      #Confirm connection to target

      #Execute test cases

      #Clean up

      #Close connections
    